config/routes.rb
TodoApp::Application.routes.draw do
  root to: "teams#index"

  resources :teams do
    resources :users, only: [:new, :create]
    resources :projects, only: [:new, :create]
  end

  resources :users do
    resources :projects, only: [:new, :create]
  end

  resources :projects do
    resources :items, only: [:new, :create]
  end

  resources :items

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :team_ids, :project_ids
  validates :username, presence: true, length: { minimum: 2 }

  has_many :team_memberships
  has_many :teams, through: :team_memberships
  has_many :projects, through: :teams
  has_many :items, through: :projects
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.assign_attributes(params[:user])

    if @user.save
      flash.notice = "#{@user.username} updated"
      redirect_to user_path(@user)
    else
      flash.now.alert = @user.errors.full_messages
      render :edit
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      flash.notice = "#{@user.username} created"
      redirect_to user_path(@user)
    else
      flash.now.alert = @user.errors.full_messages
      render :new
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash.notice = "User deleted"
    redirect_to users_path
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>

  <p>
    <%= f.label :username, "User Name" %>
    <%= f.text_field :username %>
  </p>

  <p>
    <h4>Teams</h4>
    <%= check_box_field user, Team, :name %>
  </p>

  <p>
    <%= f.submit user.persisted? ?
            "Edit that user, darling" : "Make a new user",
            class: "btn-new-update" %>
  </p>

<% end %>

<ul class="nav nav-pills">
  <li class="active">
    <%= undo user %>
  </li>
</ul>

app/views/users/edit.html.erb
<%= content_for(:title, "Edit User") %>

<h1><%= "Edit User '#{@user.username}'" %></h1>
<%= render partial: 'form', object: @user, locals: { user: @user } %>

app/views/users/index.html.erb
<%= content_for(:title, "Users") %>

<h1>Users</h1>

<ul>
  <% @users.each do |user| %>
    <li>
      <%= link_to user.username, user_path(user) %>
    </li>
  <% end %>
</ul>

<ul class="nav nav-pills">
  <li class="active">
    <%= make_new User %>
  </li>
</ul>

<%= back_to Team %>

app/views/users/new.html.erb
<%= content_for(:title, "New User") %>

<h1><%= "Make a New User" %></h1>
<%= render partial: 'form', object: @user, locals: { user: @user } %>

app/views/users/show.html.erb
<%= content_for(:title, "User") %>

<h1><%= @user.username %></h1>

<h3>Teams <%= @user.username %> belongs to</h3>
<ul>
  <% @user.teams.each do |team| %>
    <li>
      <%= link_to team.name, team_path(team) %>
    </li>
  <% end %>
</ul>

<h3>Projects</h3>
<ul>
  <% @user.projects.each do |project| %>
    <li>
      <%= link_to project.name, project_path(project) %>
    </li>
  <% end %>
</ul>

<ul class="nav nav-pills">
  <li class="active">
    <%= link_to "Edit User", edit_user_path(@user) %>
  </li>
</ul>

<%= back_to User %>