config/routes.rb
TodoApp::Application.routes.draw do
  root to: "teams#index"

  resources :teams do
    resources :users, only: [:new, :create]
    resources :projects, only: [:new, :create]
  end

  resources :users do
    resources :projects, only: [:new, :create]
  end

  resources :projects do
    resources :items, only: [:new, :create]
  end

  resources :items

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name, :description, :team_ids, :item_ids
  validates :name, presence: true

  has_many :project_teams
  has_many :teams, through: :project_teams
  has_many :users, through: :teams

  has_many :items, dependent: :destroy

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    @project.assign_attributes(params[:project])

    if @project.save
      flash.notice = "#{@project.name} updated"
      redirect_to project_path(@project)
    else
      flash.now.alert = @project.errors.full_messages
      render :edit
    end
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(params[:project])

    if @project.save
      flash.notice = "#{@project.name} created"
      redirect_to project_path(@project)
    else
      flash.now.alert = @project.errors.full_messages
      render :new
    end
  end

  def destroy
    Project.find(params[:id]).destroy
    flash.notice = "Project deleted"
    redirect_to projects_path
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
  # def item_complete_form(item)
  #   if item.completed?
  #     "Completed"
  #   else
  #     html = ""
  #     html << form_for(item) do |f|
  #       f.hidden_field :completed, true
  #       f.submit "mark complete", class: "btn-new-update"
  #     end
  #     html.html_safe
  #   end
  # end
end

app/views/projects/_form.html.erb
<%= form_for(project) do |f| %>

  <p>
    <%= f.label :name, "Project Name" %>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :description, "Description" %>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :team_ids, "Team" %>
    <%= f.collection_select :team_ids, Team.all, :id, :name %>
  </p>

  <p>
    Items
    <%= check_box_field project, Item, :title %>
  </p>

  <p>
    <%= f.submit project.persisted? ?
            "Edit that project, friend" : "Make this project",
            class: "btn-new-update" %>
  </p>

<% end %>

<ul class="nav nav-pills">
  <li class="active">
    <%= undo project %>
  </li>
</ul>

app/views/projects/edit.html.erb
<%= content_for(:title, "Edit Project") %>

<h1><%= "Edit Project '#{@project.name}'" %></h1>
<%= render partial: 'form', object: @project, locals: { project: @project } %>

app/views/projects/index.html.erb
<%= content_for(:title, "Projects") %>

<h1>Projects</h1>

<ul>
  <% @projects.each do |project| %>
    <li>
      <%= link_to project.name, project_path(project) %>
    </li>
  <% end %>
</ul>

<ul class="nav nav-pills">
  <li class="active">
    <%= make_new Project %>
  </li>
</ul>

<%= back_to Team %>

app/views/projects/new.html.erb
<%= content_for(:title, "New Project") %>

<h1><%= "Make a New Project" %></h1>
<%= render partial: 'form', object: @project, locals: { project: @project } %>

app/views/projects/show.html.erb
<%= content_for(:title, "Project") %>

<h1><%= @project.name %></h1>

<h3>Project Description</h3>
<p><%= @project.description %></p>

<h3>Teams working on <%= @project.name %></h3>
<ul>
  <% @project.teams.each do |team| %>
    <li>
      <%= link_to team.name, team_path(team) %>
    </li>
  <% end %>
</ul>

<h3>People working on <%= @project.name %></h3>
<ul>
  <% @project.users.each do |user| %>
    <li>
      <%= link_to user.username, user_path(user) %>
    </li>
  <% end %>
</ul>

<h3>Items</h3>
<ul>
  <% @project.items.each do |item| %>
    <li>
      <%= link_to item.title, item_path(item) %>
      <%#= item_complete_form(item) %>
    </li>
  <% end %>
</ul>

<ul class="nav nav-pills">
  <li class="active">
    <%= link_to "Edit Project", edit_project_path(@project) %>
    <%= link_to "DELETE", project_path(@project), method: :delete %>
  </li>
</ul>

<%= back_to Team %>