config/routes.rb
TodoApp::Application.routes.draw do
  root to: "teams#index"

  resources :teams do
    resources :users, only: [:new, :create]
    resources :projects, only: [:new, :create]
  end

  resources :users do
    resources :projects, only: [:new, :create]
  end

  resources :projects do
    resources :items, only: [:new, :create]
  end

  resources :items

end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :completed, :description, :title, :project_id
  validates :title, :project_id, presence: true

  belongs_to :project

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.assign_attributes(params[:item])

    if @item.save
      flash.notice = "#{@item.title} updated"
      redirect_to item_path(@item)
    else
      flash.now.alert = @item.errors.full_messages
      render :edit
    end
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(params[:item])

    if @item.save
      flash.notice = "#{@item.title} created"
      redirect_to item_path(@item)
    else
      flash.now.alert = @item.errors.full_messages
      render :new
    end
  end

  def destroy
    Item.find(params[:id]).destroy
    flash.notice = "Item deleted"
    redirect_to items_path
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(item) do |f| %>

  <p>
    <%= f.label :title, "Item Title" %>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description, "Description" %>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :project_id, "Project" %>
    <%= f.collection_select :project_id, Project.all, :id, :name %>
  </p>

  <p><h3>Completed?</h3>

    <label><%= f.radio_button :completed, 't', checked:
          item.completed == true ? true : false %> Yes</label>

    <label><%= f.radio_button :completed, 'f',checked:
          item.completed == false ? true : false %> No</label>
  <p>

  <p>
    <%= f.submit item.persisted? ?
            "Edit that item, friend" : "Make this item",
            class: "btn-new-update" %>
  </p>

<% end %>

<ul class="nav nav-pills">
  <li class="active">
    <%= undo item %>
  </li>
</ul>

app/views/items/edit.html.erb
<%= content_for(:title, "Edit Item") %>

<h1><%= "Edit Item '#{@item.title}'" %></h1>
<%= render partial: 'form', locals: { item: @item } %>

app/views/items/index.html.erb
<%= content_for(:title, "Items") %>

<h1>Items</h1>

<ul>
  <% @items.each do |item| %>
    <li>
      <%= link_to item.title, item_path(item) %>
    </li>
  <% end %>
</ul>

<ul class="nav nav-pills">
  <li class="active">
    <%= make_new Item %>
  </li>
</ul>

<%= back_to Project %>

app/views/items/new.html.erb
<%= content_for(:title, "New Item")%>
<h1>New Item</h1>
<%= render partial: "form", locals: { item: @item } %>

app/views/items/show.html.erb
<%= content_for(:title, "Project") %>

<h1><%= @item.title %></h1>
<h2>completed: <%= @item.completed %></h2>

<h3>Item Description</h3>
<p><%= @item.description %></p>

<h3>Teams working on <%= @item.title %></h3>
<ul>
  <% @item.project.teams.each do |team| %>
    <li>
      <%= link_to team.name, team_path(team) %>
    </li>
  <% end %>
</ul>

<h3>People working on <%= @item.title %></h3>
<ul>
  <% @item.project.users.each do |user| %>
    <li>
      <%= link_to user.username, user_path(user) %>
    </li>
  <% end %>
</ul>

<ul class="nav nav-pills">
  <li class="active">
    <%= link_to "Edit Item", edit_item_path(@item) %>
    <%= link_to "DELETE", item_path(@item), method: :delete %>
  </li>
</ul>

<%= back_to Project %>